<a href="https://colab.research.google.com/github/SDavid2312/Proyecto-Aula/blob/master/numpy2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [9]:
#vamos a crear una matirz 3x3 con datos aleatorios y vamos a sacar el maximo, el minimo, .size, .ndim
#imprimir resultados

import numpy as np

m1 = np.array([2,3,4,5,6])
m2 = np.array([11,23,43,65])
print(np.concatenate((m1,m2)))
print(" ")

m3 = np.concatenate((m1,m2))
print(m3)
print(" ")
print("valor maximo de la matriz m3 :", m3.max())
print(" ")
print("valor minimo de la matriz m3 :", m3.min())

print("numeros de componentes de la matriz :", m3.size)
print(" ")
print("dimensionalidad de la matriz :", m3.ndim)

[ 2  3  4  5  6 11 23 43 65]
 
[ 2  3  4  5  6 11 23 43 65]
 
valor maximo de la matriz m3 : 65
 
valor minimo de la matriz m3 : 2
numeros de componentes de la matriz : 9
 
dimensionalidad de la matriz : 1


In [10]:
#vamos a realizar funciones de sumas con matriz¿ces de dos dimenciones
m1 = np.array([[1,2],[3,4]])
m2 = np.array([[5,6],[7,8]])
print(m1 + m2)#realizamos las operaciones de suma con las matrices
print(" ")
#vamos a sumar un valor determinado a la matriz
print(m1 + 3)

[[ 6  8]
 [10 12]]
 
[[4 5]
 [6 7]]


In [35]:
#vamos a realizar la suma con martrices utilizando operaciones
print(np.add(m1,m2))#con la funcion . add se puede realizar la suma de las matrices

[[ 6  8]
 [10 12]]


In [33]:
print(np.subtract(m1,m2))#la funcion . subtract sirve para restar

[[-4 -4]
 [-4 -4]]


In [34]:
print(np.multiply(m1,m2))#la funcion . multiply sirve para multiplicar

[[ 5 12]
 [21 32]]


In [12]:
print(np.divide(m1,m2))# la funcion .divide sirve para dividir

[[0.2        0.33333333]
 [0.42857143 0.5       ]]


In [13]:
#vamos a crear matrices con datos aleatorios

m = np.random.randint(20, size = (5))#con la funcion randint creamos una matris con valores enteros
print(m)

[ 1 10  6 12 19]


In [14]:
#vamos a crear una matriz de dos dimenciones con valores aleatorios tipo entero
m = np.random.randint(30, size=(3,3))
print(m)

[[ 2  9  5]
 [ 5 26  6]
 [27  5 20]]


In [15]:
#podemos crear matrices con datos aleatorios decimales
m = np.random.rand(5)#con la funcion rand generamos valores decimales aleatorios
print(m)

[0.44378127 0.20956777 0.25883194 0.67427003 0.15069779]


In [16]:
m = np.random.rand(2,2)#con este comando generamos una matriz de 4 valores diferentes
print(m)

[[0.93896892 0.55927616]
 [0.30263429 0.64838288]]


In [17]:
#el .choice selecciona datos de una matriz
m = np.random.choice([32,65,43,21,33])
print(m)

21


In [18]:
m = np.random.choice([32,65,43,21,33,99,65,54,76],size = (3,3))
print(m)

[[65 21 33]
 [54 32 33]
 [43 65 99]]


Distribuciones de probabilidad

In [19]:
m = np.random.choice([32,45,76], p = [0.0,0.4,0.6], size=(1))

print(m)

[45]


In [20]:
m = np.random.choice([32,45,76], p = [0.2,0.3,0.5], size = (50))
print(m)

[76 76 45 45 32 32 76 76 32 76 76 76 32 45 76 76 45 76 45 45 45 76 76 76
 76 76 32 76 76 76 45 76 76 76 76 76 32 76 32 45 45 45 45 76 76 76 45 45
 45 45]


In [21]:
from IPython.core.prefilter import CRegExp
#funciones estadisticas con numpy

m = np.array([[1,2,3],[4,5,6],[7,8,9]])#cree la matriz
print(m)#imprimi la matriz
print(" ")
print(np.amax(m))#extraje el valor maximo de la matriz

[[1 2 3]
 [4 5 6]
 [7 8 9]]
 
9


In [22]:
m = np.array([[1,2,3],[4,5,6],[7,8,9]])#cree la matriz
print(m)#imprimi la matriz
print(" ")
print(np.amin(m))#extraje el valor minimo de la matriz


[[1 2 3]
 [4 5 6]
 [7 8 9]]
 
1


In [23]:
#eje de las matrices - eje "0" son las filas y eje "1" son las columnas
m = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(m)
print(" ")
print(np.amin(m,0))#voy a extraer el valor minimo de las filas

[[1 2 3]
 [4 5 6]
 [7 8 9]]
 
[1 2 3]


In [24]:
m = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(m)
print(" ")
print(np.amax(m,0))#voy a extraer el valor maximo de las filas

[[1 2 3]
 [4 5 6]
 [7 8 9]]
 
[7 8 9]


In [25]:
m = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(m)
print(" ")
print(np.amin(m,1))#con 1 extraemos las columnas

[[1 2 3]
 [4 5 6]
 [7 8 9]]
 
[1 4 7]


In [26]:
m = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(m)
print(" ")
print(np.amax(m,1))#voy a extraer el valor maximo de las filas

[[1 2 3]
 [4 5 6]
 [7 8 9]]
 
[3 6 9]


In [27]:
#para hallar el rango es el max - el min
m = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(m)
print(" ")
print(np.ptp(m))#con la funcion ptp extraemos el rango

[[1 2 3]
 [4 5 6]
 [7 8 9]]
 
8


In [28]:
#vamos a hallar la media de la matriz
m = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(m)
print(" ")
print(np.median(m))#voy a extraer el valor minimo de las filas

[[1 2 3]
 [4 5 6]
 [7 8 9]]
 
5.0


In [29]:
m = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(m)
print(" ")
print(np.average(m))#

[[1 2 3]
 [4 5 6]
 [7 8 9]]
 
5.0


In [30]:
m = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(m)
print(" ")
print(np.std(m))#desviiacion estandar

[[1 2 3]
 [4 5 6]
 [7 8 9]]
 
2.581988897471611


In [31]:
#como trasponer una matriz
print(m)
print(" ")
print(np.transpose(m))

[[1 2 3]
 [4 5 6]
 [7 8 9]]
 
[[1 4 7]
 [2 5 8]
 [3 6 9]]


In [32]:
#Solución de los sistemas matriciales

# AX = B - Soluciones gaussianas

A = np.array([[2,1,-2],[3,0,1],[1,1,-1]])# Matriz con los coeficientes de las ecuaciones
print(A)
print(" ")
B = np.array([[-3],[5],[2]]) # la matriz B
print(B)
print("")
print(np.transpose(B))
print(" ")
X = np.linalg.solve(A,B)
print(X)

[[ 2  1 -2]
 [ 3  0  1]
 [ 1  1 -1]]
 
[[-3]
 [ 5]
 [ 2]]

[[-3  5  2]]
 
[[-2.96059473e-16]
 [ 7.00000000e+00]
 [ 5.00000000e+00]]
